GET http://localhost:8080/categorias
###

GET http://localhost:8080/categorias/2
###

POST http://localhost:8080/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzQzNDMxLCJleHAiOjE2OTc4Mjk4MzF9.qq1kN-uEyyBblsmSDirD1Q1PMfkylcRsxakKLPGrjMc

{
    "nmCategoria": "Vestuário",
    "descricao": "Roupas e acessórios",
    "statusCate": true
}
###

POST http://localhost:8080/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzQzNDMxLCJleHAiOjE2OTc4Mjk4MzF9.qq1kN-uEyyBblsmSDirD1Q1PMfkylcRsxakKLPGrjMc

{    
    "nmCategoria": "Alimentos",
    "descricao": "Alimento para alimentar os que precisam de alimento",
    "statusCate": false
}
###

PUT http://localhost:8080/categorias/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzQzNDMxLCJleHAiOjE2OTc4Mjk4MzF9.qq1kN-uEyyBblsmSDirD1Q1PMfkylcRsxakKLPGrjMc

{
    "nmCategoria": "Vestuário",
    "descricao": "Roupas e acessórios",
    "statusCate": false
}
###

PUT http://localhost:8080/categorias/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzQzNDMxLCJleHAiOjE2OTc4Mjk4MzF9.qq1kN-uEyyBblsmSDirD1Q1PMfkylcRsxakKLPGrjMc

{    
    "nmCategoria": "Alimentos",
    "descricao": "Alimento para alimentar os que precisam de alimento",
    "statusCate": false
}
###