GET http://localhost:8080/categorias
###

GET http://localhost:8080/categorias/2
###

POST http://localhost:8080/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzY1NjkyLCJleHAiOjE2OTc4NTIwOTJ9._3XJB-M8Pz0Af8iGd3S30wQyv6LyRvDJJt2lF_rHC9Q

{
    "nmCategoria": "Vestuário",
    "descricao": "Roupas e acessórios",
    "statusCate": true
}
###

POST http://localhost:8080/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzY1NjkyLCJleHAiOjE2OTc4NTIwOTJ9._3XJB-M8Pz0Af8iGd3S30wQyv6LyRvDJJt2lF_rHC9Q

{    
    "nmCategoria": "Carros",
    "descricao": "Carros super velozes",
    "statusCate": true
}
###

PUT http://localhost:8080/categorias/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3ODI3OTQ1LCJleHAiOjE2OTc5MTQzNDV9.ujhYWoEb60Of4HLQybPaIQJXYyc8_y1VWaMicx-jErE

{
    "nmCategoria": "Vestuário",
    "descricao": "Roupas e acessórios",
    "statusCate": true
}
###

PUT http://localhost:8080/categorias/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzQzNDMxLCJleHAiOjE2OTc4Mjk4MzF9.qq1kN-uEyyBblsmSDirD1Q1PMfkylcRsxakKLPGrjMc

{    
    "nmCategoria": "Alimentos",
    "descricao": "Alimento para alimentar os que precisam de alimento",
    "statusCate": false
}
###