GET http://localhost:8080/categorias
###

GET http://localhost:8080/categorias/1
###

POST http://localhost:8080/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzM0NTAyLCJleHAiOjE2OTc4MjA5MDJ9.j195XssraOzXdJ-3LZi4rQ4xy0-IR7GLvuOsj_b5Ox4

{
    "nmCategoria": "Vestuário",
    "descricao": "Roupas e acessórios",
    "statusCate": true
}
###

POST http://localhost:8080/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzM0NTAyLCJleHAiOjE2OTc4MjA5MDJ9.j195XssraOzXdJ-3LZi4rQ4xy0-IR7GLvuOsj_b5Ox4

{    
    "nmCategoria": "Alimentos",
    "descricao": "Alimento para alimentar os que precisam de alimento",
    "statusCate": true
}
###