GET http://localhost:8080/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3ODMyNjg3LCJleHAiOjE2OTc5MTkwODd9.5rVW3fiB0pzpI7PGj2osH9DWKt7d28ZTrBclUvoM6Oc
###

GET http://localhost:8080/pedidos/2
###

POST http://localhost:8080/pedidos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3ODMyNjg3LCJleHAiOjE2OTc5MTkwODd9.5rVW3fiB0pzpI7PGj2osH9DWKt7d28ZTrBclUvoM6Oc

{
    "descontoTotal": 5,
    "acrescimoTotal": 0,
    "formaPagamento": "PIX",
    "idUsuario": 3,
    "pedidoItens": [
        {
            "produto": {
                "idProd": 1
            },
            "descProduto": 0,
            "acresProduto": 0,
            "quantidade": 1
        },
        {
            "produto": {
                "idProd": 2
            },
            "descProduto": 0,
            "acresProduto": 5,
            "quantidade": 2
        }
    ]
}
###

DELETE http://localhost:8080/pedidos/3
###

