GET http://localhost:8080/produtos
###

GET http://localhost:8080/produtos/1
###

POST http://localhost:8080/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzY1NjkyLCJleHAiOjE2OTc4NTIwOTJ9._3XJB-M8Pz0Af8iGd3S30wQyv6LyRvDJJt2lF_rHC9Q

{
  "nomeProd": "Camisetex4",
  "valorProd": 50,
  "estoqueProd": 10,
  "descricaoProd": "Camisetex brabo",
  "imgbase64Prod": "string",
  "statusProd": true,
  "idCategoria": 1
}
###

POST http://localhost:8080/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzY1NjkyLCJleHAiOjE2OTc4NTIwOTJ9._3XJB-M8Pz0Af8iGd3S30wQyv6LyRvDJJt2lF_rHC9Q

{
    "nomeProd": "Abobrinha",
    "valorProd": "1700.50",
    "estoqueProd": "10",
    "statusProd": true,
    "descricaoProd": "Abobrinha caríssima",
    "idCategoria": 4
}
###

PUT http://localhost:8080/produtos/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzM0NTAyLCJleHAiOjE2OTc4MjA5MDJ9.j195XssraOzXdJ-3LZi4rQ4xy0-IR7GLvuOsj_b5Ox4

{
    "nomeProd": "AbobrinhaAlterada",
    "valorProd": "1700.50",
    "estoqueProd": "10",
    "statusProd": true,
    "descricaoProd": "Abobrinha caríssima",
    "idCategoria": 1
}