GET http://localhost:8080/produtos
###

GET http://localhost:8080/produtos/1
###

POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nomeProd": "Sabonete",
  "valorProd": 2,
  "estoqueProd": 50,
  "descricaoProd": "Sabonete Cheiroso",
  "imgbase64Prod": "string",
  "statusProd": true,
  "idCategoria": 1
}
###

POST http://localhost:8080/produtos
Content-Type: application/json

{
    "nomeProd": "Abobrinha",
    "valorProd": "1700.50",
    "estoqueProd": "10",
    "statusProd": true,
    "descricaoProd": "Abobrinha caríssima"
}
