GET http://localhost:8080/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3Njg1NjY1LCJleHAiOjE2OTc3NzIwNjV9.QAbYJAnVQXJa9pHVWwq_HkfuFEWatTdWxpAVTTfDKSI
Content-Type: application/json
###

GET http://localhost:8080/usuarios/1
###

POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nmUsuario": "Rorivaldo1",
    "login": "rorivaldinho1",
    "senha": "1234567",
    "email": "rorivadfg1@gmail.com",
    "telefone": "219929456290",
    "perfil": "ADMIN"
}
###

POST http://localhost:8080/usuarios/login
Content-Type: application/json

{
    "email": "rorivadfg1@gmail.com",
    "senha": "1234567"
}

###

POST http://localhost:8080/usuarios/login
Content-Type: application/json

{
    "email": "ornellas00@hotmail.com",
    "senha": "12345687"
}

###

i'm having lunch rn teache
POST http://localhost:8080/usuarios/login
Content-Type: application/json

{
    "nmUsuario": "Rorivaldo3",
    "login": "rorivaldinho3",
    "senha": "1234567",
    "email": "rorivadfg3@gmail.com",
    "telefone": "219929456293",
    "perfil": "ADMIN"
}
###

PUT http://localhost:8080/usuarios/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzM0Mjc3LCJleHAiOjE2OTc4MjA2Nzd9.MF2KKraqqiBv2eRpvUowocFUTnnVpFYwE6Zq4FU8y00
Content-Type: application/json

{
    "nmUsuario": "Rorivaldo1",
    "login": "rorivaldinho1",
    "senha": "1234567",
    "email": "rorivadfg1@gmail.com",
    "telefone": "219929456290",
    "perfil": "ADMIN"
}
###